load("//go/private/rules:library.bzl", "go_tool_library")

go_tool_library(
    name = "branchcoverdata",
    srcs = ["branchcoverdata.go"],
    importpath = "github.com/bazelbuild/rules_go/go/tools/branchcoverdata",
    visibility = ["//visibility:public"],
)

filegroup(
    name = "all_files",
    testonly = True,
    srcs = glob(["**"]),
    visibility = ["//visibility:public"],
)
